### ISSUE TITLE
Failed to run server 

### ISSUE THREAD

**Issue by abdul-kowy** [morgante/django-graph-auth#3] opened 2017-01-13 17:16 UTC
First of all, thanks for your work 👍 
I followed all your instructions though my server was unable to run. Got this:

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03E275D0>
Traceback (most recent call last):
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\USER\test\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\USER\git\AjeServer\AjeServer\AjeServer\urls.py", line 4, in <module>
    from .schema import schema
  File "C:\Users\USER\git\AjeServer\AjeServer\AjeServer\schema.py", line 30, in <module>
    schema = graphene.Schema(query=Query)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\schema.py", line 39, in __init__
    self.build_typemap()
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\schema.py", line 97, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 56, in __init__
    super(TypeMap, self).__init__(types)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphql\type\typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 76, in graphene_reducer
    return self.construct_objecttype(map, type)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 147, in construct_objecttype
    map[type._meta.name]._fields = self.construct_fields_for_type(map, type)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 208, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 64, in reducer
    return self.graphene_reducer(map, type)
  File "C:\Users\Abdoul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\graphene\types\typemap.py", line 73, in graphene_reducer
    assert _type.graphene_type == type
AssertionError

**I have django 1.10.4 and install all the required packages(Graphene-Django, django-filter, django-graph-auth**

**Comment by morgante** [comment] 2017-01-15 00:17
Could you clarify what versions of those packages you use?

**Comment by abdul-kowy** [comment] 2017-01-15 00:30
Here is the list of packages i'am using

django-graph-auth (0.3.1)
django-filter (1.0.1)
graphene-django (1.2.1)

Thanks for the quick response

2017-01-15 1:17 GMT+01:00 Morgante Pell <notifications@github.com>:

**Comment by morgante** [comment] 2017-02-21 15:49
I'm going to need more information to solve this. What triggers the error?

**Comment by dervos** [comment] 2017-06-07 20:36
I think this is caused by the usage of django models where graphene objecttypes are expected. Could you show us your schema.py?

**Comment by morgante** [comment] 2017-08-16 02:20
Since we haven't seen any updates on this or additional info to debug the issue, I'm closing it. @abdul-kowy Feel free to re-open if you have more details.

**Closed by morgante** 2017-08-16 02:20 UTC
